# 本节操作-数据预处理

## 读取数据集

为了能用深度学习来解决现实世界的问题，我们经常从预处理原始数据开始， 而不是从那些准备好的张量格式数据开始。 在Python中常用的数据分析工具中，我们通常使用pandas软件包。 像庞大的Python生态系统中的许多其他扩展包一样，pandas可以与张量兼容。

In [15]:
import pandas as pd
import torch.distributed.rpc

df=pd.read_csv("./data_people.csv")
print(df.head())

   user_id name   age city  monthly_income register_date
0        1   张三   NaN   北京        15890.78    2025-08-15
1        2   李四  28.0  NaN             NaN    2025-11-22
2        3   王五  45.0   上海        32567.91    2025-05-08
3        4   赵六  36.0   广州             NaN    2025-09-30
4        5   钱七   NaN   深圳         8950.25    2025-07-12

## 处理缺失值

用pandas处理缺失的数据时，我们可根据情况选择用插值法和删除法。

In [16]:
# 切分数据集
inputs,outputs=df.iloc[:,1:2],df.iloc[:,2:]
outputs

    age city  monthly_income register_date
0   NaN   北京        15890.78    2025-08-15
1  28.0  NaN             NaN    2025-11-22
2  45.0   上海        32567.91    2025-05-08
3  36.0   广州             NaN    2025-09-30
4   NaN   深圳         8950.25    2025-07-12
5  52.0  NaN        45800.60    2025-03-18
6  23.0   杭州         6780.40    2025-12-05
7   NaN  NaN        22500.88    2025-01-20
8  41.0   成都             NaN    2025-06-28
9  33.0   武汉        18900.35    2025-04-11

In [17]:
# 替换outputs之中的缺失数值
# (1)[平均值替换]替换年龄缺失值
mean_age=int(outputs["age"].mean())
print(mean_age,type(mean_age))
outputs["age"]=outputs["age"].fillna(mean_age)
# (2)[默认数值替换]替换性别缺失值
outputs["city"]=outputs["city"].fillna("上海")
outputs

36 <class 'int'>

    age city  monthly_income register_date
0  36.0   北京        15890.78    2025-08-15
1  28.0   上海             NaN    2025-11-22
2  45.0   上海        32567.91    2025-05-08
3  36.0   广州             NaN    2025-09-30
4  36.0   深圳         8950.25    2025-07-12
5  52.0   上海        45800.60    2025-03-18
6  23.0   杭州         6780.40    2025-12-05
7  36.0   上海        22500.88    2025-01-20
8  41.0   成都             NaN    2025-06-28
9  33.0   武汉        18900.35    2025-04-11

## 替换为张量模式

In [18]:
res=outputs.iloc[:,2]
torch.tensor(res.to_numpy(dtype=float))

tensor([15890.7800,        nan, 32567.9100,        nan,  8950.2500, 45800.6000,
         6780.4000, 22500.8800,        nan, 18900.3500], dtype=torch.float64)